import Head from 'next/head';
import Faq from '../components/Faq';
import { Wrapper } from '../components/Wrapper';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Aalto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen flex justify-center">
        <div className="max-w-xl">
          <div className="min-w-full">
            <Wrapper />
          </div>
          <div className="min-w-full mt-8">
            <Faq />
          </div>
        </div>
      </main>
    </div>
  )
}
